/** LOGGED IN CHECK */
export const LOGIN_CHECK = 'LOGIN_CHECK';

/** SEND OTP */
export const SEND_OTP_BEGIN = 'SEND_OTP_BEGIN';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';

/** VERIFY OTP */
export const VERIFY_OTP_BEGIN = 'VERIFY_OTP_BEGIN';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';

/** CREATE NEW PERSON */
export const CREATE_NEW_PERSON_BEGIN = 'CREATE_NEW_PERSON_BEGIN';
export const CREATE_NEW_PERSON_SUCCESS = 'CREATE_NEW_PERSON_SUCCESS';
export const CREATE_NEW_PERSON_ERROR = 'CREATE_NEW_PERSON_ERROR';

/** CREATE NEW VENUE */
export const CREATE_NEW_VENUE_BEGIN = 'CREATE_NEW_VENUE_BEGIN';
export const CREATE_NEW_VENUE_SUCCESS = 'CREATE_NEW_VENUE_SUCCESS';
export const CREATE_NEW_VENUE_ERROR = 'CREATE_NEW_VENUE_ERROR';

/** UPDATE PERSON */
export const UPDATE_PERSON_BEGIN = 'UPDATE_PERSON_BEGIN';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_ERROR = 'UPDATE_PERSON_ERROR';

/** MY DETAILS PERSON */
export const MY_DETAILS_PERSON_BEGIN = 'MY_DETAILS_PERSON_BEGIN';
export const MY_DETAILS_PERSON_SUCCESS = 'MY_DETAILS_PERSON_SUCCESS';
export const MY_DETAILS_PERSON_ERROR = 'MY_DETAILS_PERSON_ERROR';

/** GET PERSON BY ID */
export const GET_PERSON_BY_ID_BEGIN = 'GET_PERSON_BY_ID_BEGIN';
export const GET_PERSON_BY_ID_SUCCESS = 'GET_PERSON_BY_ID_SUCCESS';
export const GET_PERSON_BY_ID_ERROR = 'GET_PERSON_BY_ID_ERROR';

/** DISCOVER */
export const DISCOVER_BEGIN = 'DISCOVER_BEGIN';
export const DISCOVER_SUCCESS = 'DISCOVER_SUCCESS';
export const DISCOVER_ERROR = 'DISCOVER_ERROR';

/** EXPLORE */
export const EXPLORE_BEGIN = 'EXPLORE_BEGIN';
export const EXPLORE_SUCCESS = 'EXPLORE_SUCCESS';
export const EXPLORE_ERROR = 'EXPLORE_ERROR';

/** GET EVENT BY ID */
export const GET_EVENT_BY_ID_BEGIN = 'GET_EVENT_BY_ID_BEGIN';
export const GET_EVENT_BY_ID_SUCCESS = 'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_ERROR = 'GET_EVENT_BY_ID_ERROR';

/** GET EVENT BY INVITE ID */
export const GET_EVENT_BY_INVITE_ID_BEGIN = 'GET_EVENT_BY_INVITE_ID_BEGIN';
export const GET_EVENT_BY_INVITE_ID_SUCCESS = 'GET_EVENT_BY_INVITE_ID_SUCCESS';
export const GET_EVENT_BY_INVITE_ID_ERROR = 'GET_EVENT_BY_INVITE_ID_ERROR';

/** GET INVITE DETAILS */
export const GET_INVITE_DETAILS_BY_INVITE_ID_BEGIN = 'GET_INVITE_DETAILS_BY_INVITE_ID_BEGIN';
export const GET_INVITE_DETAILS_BY_INVITE_ID_SUCCESS = 'GET_INVITE_DETAILS_BY_INVITE_ID_SUCCESS';
export const GET_INVITE_DETAILS_BY_INVITE_ID_ERROR = 'GET_INVITE_DETAILS_BY_INVITE_ID_ERROR';

/** GET ARTIST BY ID */
export const GET_ARTIST_BY_ID_BEGIN = 'GET_ARTIST_BY_ID_BEGIN';
export const GET_ARTIST_BY_ID_SUCCESS = 'GET_ARTIST_BY_ID_SUCCESS';
export const GET_ARTIST_BY_ID_ERROR = 'GET_ARTIST_BY_ID_ERROR';

/** CREATE INVITE */
export const CREATE_INVITE_BEGIN = 'CREATE_INVITE_BEGIN';
export const CREATE_INVITE_SUCCESS = 'CREATE_INVITE_SUCCESS';
export const CREATE_INVITE_ERROR = 'CREATE_INVITE_ERROR';

/** ACCEPT INVITE */
export const ACCEPT_INVITE_BEGIN = 'ACCEPT_INVITE_BEGIN';
export const ACCEPT_INVITE_SUCCESS = 'ACCEPT_INVITE_SUCCESS';
export const ACCEPT_INVITE_ERROR = 'ACCEPT_INVITE_ERROR';

/** DECLINE INVITE */
export const DECLINE_INVITE_BEGIN = 'DECLINE_INVITE_BEGIN;'
export const DECLINE_INVITE_SUCCESS = 'DECLINE_INVITE_SUCCESS';
export const DECLINE_INVITE_ERROR = 'DECLINE_INVITE_ERROR';

/** CREATE ACCEPT INVITE */
export const CREATE_ACCEPT_INVITE_BEGIN = 'CREATE_ACCEPT_INVITE_BEGIN';
export const CREATE_ACCEPT_INVITE_SUCCESS = 'CREATE_ACCEPT_INVITE_SUCCESS';
export const CREATE_ACCEPT_INVITE_ERROR = 'CREATE_ACCEPT_INVITE_ERROR';
